# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0018_list_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Unique code of this requirement')),
                ('name', models.CharField(max_length=256, verbose_name='Name of this requirement')),
                ('description', models.TextField(help_text='Long description of this requirement describing behavior or pointing to other resources.', verbose_name='Description of this requirement')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='boards.Board', verbose_name='Board')),
                ('cards', models.ManyToManyField(related_name='requirements', to='boards.Card', verbose_name='Tasks that depend on this requirement')),
            ],
        ),
    ]
