# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_requirement_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='comments',
            new_name='other_comments',
        ),
    ]
