# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0071_auto_20170530_1711'),
        ('recurrent_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecurrentcard',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='weeklyrecurrentcard',
            name='move_on_deadline_to_list',
        ),
        migrations.AddField(
            model_name='weeklyrecurrentcard',
            name='move_to_list_when_day_ends',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moved_recurrent_cards', to='boards.List', verbose_name='Automatically move the card to this list when the day ends'),
        ),
        migrations.AlterField(
            model_name='recurrentcard',
            name='estimated_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Estimated time that will be spent in this card', max_digits=10, null=True, verbose_name='Estimated spent time of this recurrent card'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_fridays',
            field=models.BooleanField(default=False, verbose_name='Create card on fridays'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_mondays',
            field=models.BooleanField(default=False, verbose_name='Create card on mondays'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_saturdays',
            field=models.BooleanField(default=False, verbose_name='Create card on saturdays'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_sundays',
            field=models.BooleanField(default=False, verbose_name='Create card on sundays'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_thursdays',
            field=models.BooleanField(default=False, verbose_name='Create card on thursdays'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_tuesdays',
            field=models.BooleanField(default=False, verbose_name='Create card on tuesdays'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurrentcard',
            name='create_on_wednesdays',
            field=models.BooleanField(default=False, verbose_name='Create card on wednesdays'),
        ),
    ]
