# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrent_cards', '0002_auto_20170602_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentcard',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If unchecked, no cards will be created that depends on this recurrent card', verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='recurrentcard',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='recurrent_cards', to='boards.Label'),
        ),
        migrations.AlterField(
            model_name='recurrentcard',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='recurrent_cards', to='members.Member', verbose_name='Members'),
        ),
    ]
