# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiboards', '0004_auto_20170526_1615'),
        ('members', '0023_auto_20170519_1715'),
        ('boards', '0068_auto_20170515_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHoursPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of this package')),
                ('description', models.TextField(help_text='Long description of this pakage describing thetype of work the workers must do', verbose_name='Description of this package')),
                ('number_of_hours', models.PositiveIntegerField(help_text='Number of hours of this package.', verbose_name='Number of hours')),
                ('is_paid', models.BooleanField(default=False, help_text='Has the client paid for this package', verbose_name='Is this package paid?')),
                ('payment_datetime', models.DateField(blank=True, default=None, null=True, verbose_name='When this package was paid')),
                ('start_work_date', models.DateField(verbose_name='Start date')),
                ('end_work_date', models.DateField(verbose_name='End date')),
                ('board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_hours_packages', to='boards.Board', verbose_name='Board')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_hours_packages', to='members.Member', verbose_name='Member')),
                ('label', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_hours_packages', to='boards.Label', verbose_name='Label')),
                ('members', models.ManyToManyField(blank=True, related_name='work_hours_packages', to='members.Member', verbose_name='Member')),
                ('multiboard', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_hours_packages', to='multiboards.Multiboard', verbose_name='Multiboard')),
            ],
        ),
    ]
