# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhourspackage',
            old_name='payment_datetime',
            new_name='payment_date',
        ),
    ]
