# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0003_workhourspackage_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhourspackage',
            name='completion_notification_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Notification was sent in this date and time'),
        ),
        migrations.AddField(
            model_name='workhourspackage',
            name='notify_on_completion',
            field=models.BooleanField(blank=True, default=False, max_length=254, verbose_name='Notify the members and this email on completion'),
        ),
    ]
