# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0004_auto_20170526_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhourspackage',
            name='extra_hours',
            field=models.IntegerField(blank=True, default=0, help_text='Include the number of hours', verbose_name='Extra hours'),
        ),
        migrations.AddField(
            model_name='workhourspackage',
            name='extra_hours_description',
            field=models.TextField(blank=True, default='', help_text='Provide a description of the tasks that were done in this hours', verbose_name='Extra hours description'),
        ),
        migrations.AlterField(
            model_name='workhourspackage',
            name='notify_on_completion',
            field=models.BooleanField(default=False, verbose_name='Notify the members and this email on completion'),
        ),
    ]
