# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0005_auto_20170529_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhourspackage',
            name='extra_hours',
        ),
        migrations.RemoveField(
            model_name='workhourspackage',
            name='extra_hours_description',
        ),
        migrations.AddField(
            model_name='workhourspackage',
            name='offset_hours',
            field=models.IntegerField(blank=True, default=0, help_text='This hours will be added as an initial offset of the spent time measurementsgotten in the date interval', verbose_name='Offset hours'),
        ),
        migrations.AddField(
            model_name='workhourspackage',
            name='offset_hours_description',
            field=models.TextField(blank=True, default='', help_text='Provide a description of the tasks that were done in this hours', verbose_name='Offset hours description'),
        ),
    ]
