# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0008_auto_20170529_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhourspackage',
            name='eighty_percent_completion_notification_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='80% notification was sent in this date and time'),
        ),
        migrations.AddField(
            model_name='workhourspackage',
            name='half_completion_notification_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='50% notification was sent in this date and time'),
        ),
        migrations.AddField(
            model_name='workhourspackage',
            name='ninety_percent_completion_notification_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='90% notification was sent in this date and time'),
        ),
    ]
