# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_type(apps, schema):
    WorkHoursPackage = apps.get_model("work_hours_packages", "WorkHoursPackage")
    for package in WorkHoursPackage.objects.all():
        if package.board:
            package.type = "board"
            package.save()
        elif package.multiboard:
            package.type = "multiboard"
            package.save()
        elif package.label:
            package.type = "label"
            package.save()


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0009_auto_20170530_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhourspackage',
            name='type',
            field=models.CharField(choices=[('board', 'Board'), ('multiboard', 'Multiboard'), ('label', 'Label')], default='board', max_length=256, verbose_name='Type of this package'),
            preserve_default=False,
        ),
        migrations.RunPython(set_type),
        migrations.AlterField(
            model_name='workhourspackage',
            name='board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hours_packages', to='boards.Board', verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='workhourspackage',
            name='label',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hours_packages', to='boards.Label', verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='workhourspackage',
            name='multiboard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hours_packages', to='multiboards.Multiboard', verbose_name='Multiboard'),
        ),
    ]
