# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_hours_packages', '0010_auto_20170530_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhourspackage',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Long description of this pakage describing thetype of work the workers must do', verbose_name='Description of this package'),
        ),
        migrations.AlterField(
            model_name='workhourspackage',
            name='type',
            field=models.CharField(choices=[('board', 'Board'), ('multiboard', 'Multiboard'), ('label', 'Label')], help_text='A work hours package depends on a board, multiboard or label. It depends on the project, the default option if selecting a label for each package', max_length=256, verbose_name='Type of this package'),
        ),
    ]
