# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_auto_20160823_1808'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('forward', 'Forward'), ('backward', 'Backward')], max_length=32, verbose_name='Movement type')),
                ('date', models.DateTimeField(verbose_name='Date and time this card has been moved')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='boards.Board', verbose_name='Board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='boards.Card', verbose_name='Board')),
                ('destination_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_lists', to='boards.List', verbose_name='Destination list')),
                ('source_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_lists', to='boards.List', verbose_name='Source list')),
            ],
        ),
    ]
