# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_cardmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmovement',
            old_name='date',
            new_name='datetime',
        ),
    ]
