# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_auto_20160925_1809'),
        ('reports', '0004_auto_20160904_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmovement',
            options={'verbose_name': 'Card movement', 'verbose_name_plural': 'Card movements'},
        ),
        migrations.AlterIndexTogether(
            name='cardmovement',
            index_together=set([('board', 'card', 'datetime'), ('board', 'type', 'source_list', 'destination_list'), ('board', 'destination_list', 'datetime')]),
        ),
    ]
