# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def delete_all_card_movements(apps, schema):
    CardMovement = apps.get_model("reports", "CardMovement")
    CardMovement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20160923_2056'),
        ('reports', '0006_auto_20161009_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmovement',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_movements', to='members.Member', verbose_name='Member'),
        ),
        migrations.RunPython(delete_all_card_movements)
    ]
