# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170211_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listreport',
            name='board',
        ),
        migrations.RemoveField(
            model_name='listreport',
            name='list',
        ),
        migrations.DeleteModel(
            name='ListReport',
        ),
    ]
