# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_reportrecipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportrecipient',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='reportrecipient',
            name='send_errors',
            field=models.BooleanField(default=False, help_text='Only report recipients with this option enabled will receive 500 error notifications', verbose_name='Send platform errors?'),
        ),
    ]
