# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170325_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecipient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Name of this recipient'),
        ),
        migrations.AddField(
            model_name='reportrecipient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Last name of this recipient'),
        ),
    ]
