version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=djanban
      - MYSQL_ROOT_PASSWORD=djanban
      - MYSQL_USER=djanban
      - MYSQL_PASSWORD=djanban
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=djanban.settings
      - DATABASE_URL=mysql://djanban:djanban@db:3306/djanban
      - MYSQL_DATABASE=djanban
      - MYSQL_USER=djanban
      - MYSQL_PASSWORD=djanban
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy
