# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0061_auto_20170321_0236'),
        ('members', '0021_auto_20170319_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Notification description')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is this notification read?')),
                ('reading_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='When this notification was read')),
                ('creation_datetime', models.DateTimeField(verbose_name='Creation datetime')),
                ('board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='boards.Board', verbose_name='Board this notification belongs to')),
                ('card', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='boards.Card', verbose_name='Card this notification belongs to')),
                ('card_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='boards.CardComment', verbose_name='Card comment this notification belongs to')),
                ('list', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='boards.List', verbose_name='List this notification belongs to')),
                ('receiver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to='members.Member', verbose_name='Receiver of this notification')),
                ('sender', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='members.Member', verbose_name='Sender of this notification')),
            ],
        ),
    ]
