# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0030_auto_20160925_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAgilityRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.CharField(choices=[('1', '0% Level 1B / 35% Level 2 and 3'), ('2', '10% Level 1B / 30% Level 2 and 3'), ('3', '20% Level 1B / 25% Level 2 and 3'), ('4', '30% Level 1B / 20% Level 2 and 3'), ('5', '40% Level 1B / 15% Level 2 and 3')], help_text='Personnel dimension in extended Cockburn scale', max_length=64, verbose_name='Personnel')),
                ('dynamism', models.CharField(choices=[('50', '50'), ('30', '30'), ('10', '10'), ('5', '5'), ('1', '1')], help_text='Percentage of changes per month', max_length=64, verbose_name='Dynamism')),
                ('culture', models.CharField(choices=[('90', '90'), ('70', '70'), ('50', '50'), ('30', '30'), ('10', '10')], help_text='Thriving on chaos vs. order', max_length=64, verbose_name='Culture')),
                ('size', models.CharField(choices=[('3', '3'), ('10', '10'), ('30', '30'), ('100', '100'), ('300', '300')], help_text='Number of personnel', max_length=64, verbose_name='Culture')),
                ('criticality', models.CharField(choices=[('comfort', 'comfort'), ('discretionary-funds', 'Discretionary funds'), ('essential-funds', 'Essential funds'), ('single-life', 'Single life'), ('many-lives', 'Many lives')], help_text='Consequences of a software defect', max_length=64, verbose_name='Criticality')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agility_rating', to='boards.Board', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'project agility rating',
                'verbose_name_plural': 'project agility ratings',
            },
        ),
    ]
