# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0009_auto_20160727_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the workflow')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='boards.Board', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card cycle card time')),
                ('cycle_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card lead time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='boards.Board', verbose_name='Board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='boards.Card', verbose_name='Card')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='workflows.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order of the list')),
                ('is_done_list', models.BooleanField(default=False, verbose_name='Informs if the list is a done list')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_list', to='boards.List', verbose_name='List')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_lists', to='workflows.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='lists',
            field=models.ManyToManyField(related_name='workflow', through='workflows.WorkflowList', to='boards.List'),
        ),
    ]
