# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0064_auto_20170402_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=32, verbose_name='Regression model')),
                ('formula', models.TextField(verbose_name='Formula')),
                ('results_file', models.FileField(upload_to=b'', verbose_name='Field with the statsmodels results')),
                ('board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasters', to='boards.Board', verbose_name='Board of this forecaster')),
            ],
        ),
    ]
