# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecaster',
            name='last_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 21, 16, 28, 258729, tzinfo=utc), verbose_name='Last update datetime'),
            preserve_default=False,
        ),
    ]
