# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20170319_1438'),
        ('forecaster', '0002_forecaster_last_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecaster',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasters', to='members.Member', verbose_name='Member of this forecaster'),
        ),
        migrations.AddField(
            model_name='forecaster',
            name='name',
            field=models.CharField(default='Regression model', max_length=1024, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
