# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0003_auto_20170404_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecaster',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Summary'),
        ),
    ]
