# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0064_auto_20170402_2123'),
        ('forecaster', '0004_forecaster_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_spent_time', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Estimated spent time')),
                ('last_update_datetime', models.DateTimeField(verbose_name='Date this estimation was done')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='boards.Card', verbose_name='Card for this forecast')),
                ('forecaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecaster.Forecaster', verbose_name='Spent time for this forecast')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together=set([('forecaster', 'card')]),
        ),
    ]
