# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the board')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='Trello id of the board')),
                ('last_activity_date', models.DateTimeField(default=None, null=True, verbose_name='Last activity date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to='members.Member', verbose_name='Member')),
                ('members', models.ManyToManyField(related_name='boards', to='members.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the card')),
                ('uuid', models.CharField(max_length=128, verbose_name='Trello id of the card')),
                ('url', models.CharField(max_length=128, verbose_name='URL of the card')),
                ('short_url', models.CharField(max_length=128, verbose_name='Short URL of the card')),
                ('description', models.TextField(verbose_name='Description of the card')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is this card closed?')),
                ('position', models.PositiveIntegerField(verbose_name='Position in the list')),
                ('last_activity_date', models.DateTimeField(verbose_name='Last activity date')),
                ('spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Actual card spent time')),
                ('estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Estimated card completion time')),
                ('cycle_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Lead time')),
                ('lead_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Cycle time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.Board', verbose_name='Board')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of the time measurement')),
                ('day_of_year', models.CharField(max_length=16, verbose_name='Day number of the time measurement')),
                ('week_of_year', models.CharField(max_length=16, verbose_name='Week number of the time measurement')),
                ('weekday', models.CharField(max_length=16, verbose_name='Week day of the time measurement')),
                ('spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card spent time for this card')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='boards.Board', verbose_name='Board')),
            ],
        ),
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(verbose_name='Date this object was created')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetches', to='boards.Board', verbose_name='Board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the label')),
                ('uuid', models.CharField(max_length=128, verbose_name='Trello id of the label')),
                ('color', models.CharField(max_length=128, verbose_name='Color of the label')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.Board', verbose_name='Board')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.Fetch', verbose_name='Fetch')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the board')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='Trello id of the list')),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('development', 'In development'), ('done', 'Done')], default='normal', max_length=64)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.Board', verbose_name='Board')),
            ],
        ),
        migrations.CreateModel(
            name='ListReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_movements', models.PositiveIntegerField(verbose_name='Forward movements')),
                ('backward_movements', models.PositiveIntegerField(verbose_name='Backward movements')),
                ('avg_card_time', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Average time cards live in this list')),
                ('std_dev_card_time', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Average time cards live in this list')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.Fetch', verbose_name='Fetch')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.List', verbose_name='List')),
            ],
        ),
        migrations.CreateModel(
            name='MemberReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.PositiveIntegerField(default=0, verbose_name='Number of assigned cards')),
                ('forward_movements', models.PositiveIntegerField(verbose_name='Forward movements')),
                ('backward_movements', models.PositiveIntegerField(verbose_name='Backward movements')),
                ('avg_card_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average time a card lives in the board')),
                ('std_dev_card_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Dev. time a card lives in the board')),
                ('avg_card_spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average card spent time')),
                ('std_dev_card_spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Deviation card spent time')),
                ('avg_card_estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average task estimated card completion time')),
                ('std_dev_estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Deviation of the estimated card completion time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='boards.Board', verbose_name='Board')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='boards.Fetch', verbose_name='Fetch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='members.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the workflow')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='boards.Board', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card cycle card time')),
                ('cycle_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card lead time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='boards.Board', verbose_name='Board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='boards.Card', verbose_name='Card')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='boards.Fetch', verbose_name='Fetch')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_card_reports', to='boards.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order of the list')),
                ('is_done_list', models.BooleanField(default=False, verbose_name='Informs if the list is a done list')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_list', to='boards.List', verbose_name='List')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_lists', to='boards.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='lists',
            field=models.ManyToManyField(related_name='workflow', through='boards.WorkflowList', to='boards.List'),
        ),
        migrations.AddField(
            model_name='dailyspenttime',
            name='fetch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='boards.Fetch', verbose_name='Fetch'),
        ),
        migrations.AddField(
            model_name='dailyspenttime',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='members.Member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='card',
            name='fetch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.Fetch', verbose_name='Fetch'),
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(related_name='cards', to='boards.Label'),
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.List', verbose_name='List'),
        ),
        migrations.AlterUniqueTogether(
            name='listreport',
            unique_together=set([('fetch', 'list')]),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('fetch', 'uuid')]),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('fetch', 'uuid')]),
        ),
    ]
