# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the board')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='Trello id of the board')),
                ('last_activity_date', models.DateTimeField(verbose_name='Last activity date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='members.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the board')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='Trello id of the list')),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('development', 'In development'), ('done', 'Done')], default='normal', max_length=64)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.Board', verbose_name='Board')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the workflow')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='boards.Board', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order of the list')),
                ('is_done_list', models.BooleanField(default=False, verbose_name='Informs if the list is a done list')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowlistorder', to='boards.List', verbose_name='List')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowlistorder', to='boards.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='lists',
            field=models.ManyToManyField(related_name='workflow', through='boards.WorkflowList', to='boards.List'),
        ),
    ]
