# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='last_activity_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last activity date'),
        ),
    ]
