# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='uuid',
            field=models.CharField(max_length=128, verbose_name='Trello id of the label'),
        ),
    ]
