# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20160709_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=512, verbose_name='URL of the card'),
        ),
    ]
