# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20160705_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_movements', models.PositiveIntegerField(verbose_name='Forward movements')),
                ('backward_movements', models.PositiveIntegerField(verbose_name='Backward movements')),
                ('avg_card_time', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Average time cards live in this list')),
                ('std_dev_card_time', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Average time cards live in this list')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.Fetch', verbose_name='Fetch')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.List', verbose_name='List')),
            ],
        ),
    ]
