# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20160703_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlist',
            name='name',
            field=models.CharField(default='x', max_length=128, verbose_name='Name of the list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowlist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowlist', to='boards.List', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='workflowlist',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowlists', to='boards.Workflow', verbose_name='Workflow'),
        ),
    ]
