# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20160709_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.TextField(verbose_name='Name of the card'),
        ),
    ]
