# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160707_0034'),
        ('boards', '0003_listreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member',
        ),
        migrations.AddField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to='members.Member', verbose_name='Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to='members.Member', verbose_name='Member'),
        ),
    ]
