# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20160703_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlist',
            name='name',
        ),
    ]
