# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_workflowlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the card')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='Trello id of the card')),
                ('url', models.CharField(max_length=128, verbose_name='URL of the card')),
                ('short_url', models.CharField(max_length=128, verbose_name='Short URL of the card')),
                ('description', models.TextField(verbose_name='Description of the card')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is this card closed?')),
                ('position', models.PositiveIntegerField(verbose_name='Position in the list')),
                ('last_activity_date', models.DateTimeField(verbose_name='Last activity date')),
                ('spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Actual card spent time')),
                ('estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Estimated card completion time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.Board', verbose_name='Board')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.List', verbose_name='List')),
            ],
        ),
    ]
