# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_billing_rate_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='billing_rate_per_hour',
        ),
        migrations.AddField(
            model_name='board',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=128, verbose_name='Comments for this board'),
        ),
    ]
