# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20160709_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyspenttime',
            name='board',
        ),
        migrations.RemoveField(
            model_name='dailyspenttime',
            name='fetch',
        ),
        migrations.RemoveField(
            model_name='dailyspenttime',
            name='member',
        ),
        migrations.DeleteModel(
            name='DailySpentTime',
        ),
    ]
