# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the label')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='Trello id of the label')),
                ('color', models.CharField(max_length=128, verbose_name='Color of the label')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.Board', verbose_name='Board')),
            ],
        ),
    ]
