# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20160710_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberreport',
            old_name='std_dev_estimated_time',
            new_name='std_dev_card_estimated_time',
        ),
    ]
