# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_rates', '0001_initial'),
        ('boards', '0005_auto_20160719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hourly_rates',
            field=models.ManyToManyField(related_name='boards', to='hourly_rates.HourlyRate', verbose_name='Hourly rates'),
        ),
    ]
