# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20160710_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listreport',
            name='avg_card_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average time cards live in this list'),
        ),
        migrations.AlterField(
            model_name='listreport',
            name='std_dev_card_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average time cards live in this list'),
        ),
    ]
