# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(related_name='cards', to='boards.Label'),
        ),
    ]
