# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20160707_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberreport',
            name='number_of_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of assigned cards'),
        ),
    ]
