# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_memberreport_number_of_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_card_lead_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average cycle card time')),
                ('std_dev_card_lead_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Dev. for card cycle time')),
                ('avg_card_cycle_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average lead time')),
                ('std_dev_card_cycle_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Dev. for card lead time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reports', to='boards.Board', verbose_name='Board')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reports', to='boards.Fetch', verbose_name='Fetch')),
            ],
        ),
    ]
