# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_workflowreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card cycle card time')),
                ('cycle_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card lead time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reports', to='boards.Board', verbose_name='Board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reports', to='boards.Card', verbose_name='Card')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_reports', to='boards.Fetch', verbose_name='Fetch')),
            ],
        ),
        migrations.RemoveField(
            model_name='workflowreport',
            name='board',
        ),
        migrations.RemoveField(
            model_name='workflowreport',
            name='fetch',
        ),
        migrations.DeleteModel(
            name='WorkflowReport',
        ),
    ]
