# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20160726_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='board',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='workflowcardreport',
            name='board',
        ),
        migrations.RemoveField(
            model_name='workflowcardreport',
            name='card',
        ),
        migrations.RemoveField(
            model_name='workflowcardreport',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflowlist',
            name='list',
        ),
        migrations.RemoveField(
            model_name='workflowlist',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.DeleteModel(
            name='WorkflowCardReport',
        ),
        migrations.DeleteModel(
            name='WorkflowList',
        ),
    ]
