# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160707_0034'),
        ('boards', '0010_auto_20160707_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of the time measurement')),
                ('day_of_year', models.CharField(max_length=16, verbose_name='Day number of the time measurement')),
                ('week_of_year', models.CharField(max_length=16, verbose_name='Week number of the time measurement')),
                ('weekday', models.CharField(max_length=16, verbose_name='Week day of the time measurement')),
                ('spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Card spent time for this card')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='boards.Board', verbose_name='Board')),
                ('fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='boards.Fetch', verbose_name='Fetch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='members.Member', verbose_name='Member')),
            ],
        ),
        migrations.AlterField(
            model_name='workflowlist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_list', to='boards.List', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='workflowlist',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_lists', to='boards.Workflow', verbose_name='Workflow'),
        ),
    ]
