# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_board_has_to_be_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='listreport',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.Board', verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='has_to_be_fetched',
            field=models.BooleanField(default=True, help_text='Select this option if you want to fetch data for this board.', verbose_name='Has to be this board fetched?'),
        ),
        migrations.AlterField(
            model_name='board',
            name='hourly_rates',
            field=models.ManyToManyField(blank=True, related_name='boards', to='hourly_rates.HourlyRate', verbose_name='Hourly rates'),
        ),
        migrations.AlterField(
            model_name='board',
            name='uuid',
            field=models.CharField(max_length=128, unique=True, verbose_name='External id of the board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='uuid',
            field=models.CharField(max_length=128, unique=True, verbose_name='External id of the card'),
        ),
        migrations.AlterField(
            model_name='label',
            name='uuid',
            field=models.CharField(max_length=128, unique=True, verbose_name='External id of the label'),
        ),
        migrations.AlterField(
            model_name='list',
            name='uuid',
            field=models.CharField(max_length=128, unique=True, verbose_name='External id of the list'),
        ),
    ]
