# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20160805_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='estimated_number_of_hours',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Number of hours in the budget', null=True, verbose_name='Estimated number of hours to be completed'),
        ),
        migrations.AddField(
            model_name='board',
            name='percentage_of_completion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Percentage of completion'),
        ),
    ]
