# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20160808_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='short_url',
            field=models.CharField(max_length=128, unique=True, verbose_name='Short URL of the card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL of the card'),
        ),
    ]
