# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20160813_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='blocking_cards',
            field=models.ManyToManyField(related_name='blocked_cards', to='boards.Card'),
        ),
    ]
