# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_card_blocking_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position of this list in the board'),
        ),
    ]
