# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_list_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='percentage_of_completion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Percentage of completion of project. Mind the porcentage of completion of each requirement', max_digits=10, null=True, verbose_name='Percentage of completion'),
        ),
    ]
