# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0023_auto_20160904_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='Visitors of this board'),
        ),
    ]
