# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_board_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_on_slideshow',
            field=models.BooleanField(default=False, verbose_name='Should this board be shown on the slideshow?'),
        ),
    ]
