# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_board_show_on_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='show_on_slideshow',
            field=models.BooleanField(default=False, help_text='Mark this checkbox if you want to show this board in the slideshow', verbose_name='Should this board be shown on the slideshow?'),
        ),
    ]
