# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20160923_2056'),
        ('boards', '0027_cardcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='cardcomment',
            options={'verbose_name': 'Card comment', 'verbose_name_plural': 'Card comments'},
        ),
        migrations.AlterField(
            model_name='cardcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='members.Member', verbose_name='Member author of this comment'),
        ),
        migrations.AlterField(
            model_name='cardcomment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.Card', verbose_name='Card this commenb belongs to'),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together=set([('board', 'creation_datetime'), ('board', 'list', 'position')]),
        ),
        migrations.AlterIndexTogether(
            name='cardcomment',
            index_together=set([('card', 'creation_datetime', 'author'), ('author', 'card', 'creation_datetime'), ('card', 'author', 'creation_datetime'), ('creation_datetime', 'card', 'author')]),
        ),
    ]
