# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0032_auto_20161012_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived boards are not fetched automatically and are ignored', verbose_name='This board is archived'),
        ),
    ]
