# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 22:31
from __future__ import unicode_literals

from django.db import migrations


def change_in_development_list_type(apps, schema):
    List = apps.get_model("boards", "List")
    List.objects.filter(type="before_development").update(type="ready_to_develop")


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0034_auto_20161024_0025'),
    ]

    operations = [
        migrations.RunPython(change_in_development_list_type)
    ]
