# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_auto_20161024_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.CharField(default='196A3E', help_text='Background color for this board in hexadecimal', max_length=32, verbose_name='Background color for this board'),
        ),
    ]
