# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0041_card_due_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='last_edition_datetime',
            field=models.DateTimeField(default=None, verbose_name='Last edition of the comment'),
        ),
    ]
