# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0042_cardcomment_last_edition_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='blocking_card',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocking_comments', to='boards.Card', verbose_name='Blocking card this comment belongs to'),
        ),
    ]
