# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0042_cardcomment_last_edition_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomment',
            name='last_edition_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last edition of the comment'),
        ),
    ]
