# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_cardreview_description'),
        ('boards', '0043_cardcomment_blocking_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='review',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reports.CardReview', verbose_name='Card review this comment represents'),
        ),
    ]
