# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0045_cardcomment_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to='members.Member', verbose_name='Members'),
        ),
    ]
