# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0049_auto_20170213_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='url',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='URL of the board'),
        ),
    ]
