# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0052_auto_20170303_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='wip_limit',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of cards that should be in this list', verbose_name='Maximum WIP limit of this list'),
        ),
    ]
