# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0053_auto_20170311_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name of the list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='wip_limit',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Maximum number of cards that should be in this list', null=True, verbose_name='Maximum WIP limit of this list'),
        ),
    ]
