# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0055_auto_20170311_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='identicon',
            field=models.ImageField(blank=True, default=None, help_text='Identicon for this board. It is automatically generated and stored.', null=True, upload_to=b'', verbose_name='Identicon'),
        ),
        migrations.AddField(
            model_name='board',
            name='identicon_hash',
            field=models.CharField(blank=True, default='', help_text='Identicon hash used to know when to update it', max_length=256, verbose_name='Identicon hash'),
        ),
    ]
