# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models


def set_number_of_mentioned_members(apps, schema):
    CardComment = apps.get_model("boards", "CardComment")
    card_comments = CardComment.objects.all()
    for card_comment in card_comments:
        card_comment.number_of_mentioned_members = card_comment.mentioned_members.count()
        card_comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0062_auto_20170402_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='number_of_mentioned_members',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of mentioned members'),
        ),
        migrations.RunPython(set_number_of_mentioned_members)
    ]
