# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:26
from __future__ import unicode_literals
from django.db import migrations, models
import re


# Sets the number of words in comments for each card
def set_number_of_words_in_comments(apps, schema):
    Card = apps.get_model("boards", "Card")
    for card in Card.objects.all():
        card.number_of_words_in_comments = sum([len(re.split(r"\s+", comment.content)) for comment in card.comments.all()])
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0064_auto_20170402_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number_of_words_in_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of words in the comments of this card'),
        ),
        migrations.RunPython(set_number_of_words_in_comments)
    ]
