# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of the time measurement')),
                ('day_of_year', models.CharField(max_length=16, verbose_name='Day number of the time measurement')),
                ('week_of_year', models.CharField(max_length=16, verbose_name='Week number of the time measurement')),
                ('weekday', models.CharField(max_length=16, verbose_name='Week day of the time measurement')),
                ('spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Spent time for this day')),
                ('estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Estimated time for this day')),
                ('diff_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Difference between the estimated time and the spent time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='boards.Board', verbose_name='Board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spent_times', to='members.Member', verbose_name='Member')),
            ],
        ),
    ]
