# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspenttime',
            name='rate_amount',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Rate amount for this spent time'),
        ),
    ]
