# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:22


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0009_auto_20160727_2028"),
        ("dev_times", "0003_dailyspenttime_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyspenttime",
            name="card",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_spent_times",
                to="boards.Card",
                verbose_name="Card",
            ),
        ),
    ]
