# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_times', '0007_auto_20161111_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspenttime',
            name='adjusted_spent_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Adjusted spent time for this day'),
        )
    ]
