# Generated by Django 6.0.1 on 2026-01-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_times', '0010_auto_20170530_1701'),
    ]

    operations = [
        
        
        
    ]
