# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20170209_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='biography',
            field=models.TextField(blank=True, default='', verbose_name='Biography'),
        ),
    ]
