# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_members', to='members.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Check this if you want other members to add you to their boards'),
        ),
    ]
