# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_member_default_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpentTimeFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Name of this factor')),
                ('start_date', models.DateField(verbose_name='Start date of this factor')),
                ('end_date', models.DateField(default=None, null=True, verbose_name='End date of this factor')),
                ('factor', models.DecimalField(decimal_places=2, default=1, help_text='Modify this value whe this member cost needs to be adjusted by a factor', max_digits=5, verbose_name='Factor that needs to be multiplied on the spent time price for this member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spent_time_factors', to='members.Member', verbose_name='Member')),
            ],
        ),
    ]
