# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20170225_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='spent_time_factor',
        ),
    ]
