# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_member_custom_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='custom_avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'', verbose_name='Custom avatar'),
        ),
    ]
