# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20170519_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=64, null=True, verbose_name='Jira username')),
                ('password', models.CharField(default=None, max_length=64, null=True, verbose_name='Jira password')),
                ('server', models.URLField(default=None, max_length=128, null=True, verbose_name='Jira server')),
                ('member', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jira_member_profile', to='members.Member', verbose_name='Associated member')),
            ],
        ),
    ]
