# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True, verbose_name='Uuid')),
                ('creation_datetime', models.DateTimeField(verbose_name='Creation datetime')),
                ('limit_datetime', models.DateTimeField(verbose_name='Maximum life datetime')),
                ('completion_datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Completion datetime')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16, verbose_name='Status of this request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
