# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabrepository',
            options={'verbose_name': 'GitLab repository', 'verbose_name_plural': 'GitLab repositories'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Repository', 'verbose_name_plural': 'Repositories'},
        ),
    ]
