# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_auto_20160904_1643'),
        ('repositories', '0002_auto_20160906_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='LintingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, verbose_name='File where the message')),
                ('type', models.CharField(max_length=256, verbose_name='Linting type')),
                ('message', models.TextField(verbose_name='Message content')),
                ('message_symbolic_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Message content')),
                ('line', models.PositiveIntegerField(verbose_name='Line where the error happens')),
                ('column', models.PositiveIntegerField(verbose_name='Column where the error happens')),
                ('object', models.CharField(max_length=256, verbose_name='Object')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linting_messages', to='boards.Board', verbose_name='Project this linting message depends on')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linting_messages', to='repositories.Commit', verbose_name='Commit this linting message depends on')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linting_messages', to='repositories.Repository', verbose_name='Repository this linting message depends on')),
            ],
            options={
                'verbose_name': 'linting message',
                'verbose_name_plural': 'linting messages',
            },
        ),
        migrations.AlterIndexTogether(
            name='lintingmessage',
            index_together=set([('board', 'commit', 'type'), ('board', 'type'), ('commit', 'type')]),
        ),
    ]
