# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20160907_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lintingmessage',
            name='column',
            field=models.IntegerField(verbose_name='Column where the error happens'),
        ),
        migrations.AlterField(
            model_name='lintingmessage',
            name='line',
            field=models.IntegerField(verbose_name='Line where the error happens'),
        ),
    ]
