# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20160921_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='code',
        ),
    ]
