# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_remove_commit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='has_been_assesed',
            field=models.BooleanField(default=False, verbose_name='Informs if the commit code has been assessed'),
        ),
    ]
