# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_commit_has_been_assesed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='has_been_assesed',
            new_name='has_been_assessed',
        ),
    ]
