# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_auto_20160921_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='assessment_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='Assessment date and time'),
        ),
    ]
