# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_auto_20160925_1809'),
        ('repositories', '0009_auto_20160924_1700'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='commit',
            index_together=set([('board', 'repository', 'commit'), ('board', 'repository', 'creation_datetime', 'commit')]),
        ),
        migrations.AlterIndexTogether(
            name='pylintmessage',
            index_together=set([('board', 'repository', 'type', 'commit', 'commit_file'), ('board', 'commit', 'type'), ('board', 'type'), ('board', 'repository', 'commit', 'commit_file', 'type'), ('commit', 'type')]),
        ),
    ]
