# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0012_auto_20160925_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabrepository',
            name='ci_token',
        ),
        migrations.AddField(
            model_name='gitlabrepository',
            name='password',
            field=models.CharField(default='', help_text='Password of the reporter user that will be used to clone and checkout the repository', max_length=128, verbose_name='Password of the username used to clone repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gitlabrepository',
            name='username',
            field=models.CharField(default='', help_text='Username of the reporter user that will be used to clone and checkout the repository', max_length=128, verbose_name='Username used to clone repository'),
            preserve_default=False,
        ),
    ]
