# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_auto_20160925_1809'),
        ('dev_times', '0004_dailyspenttime_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyspenttime',
            options={'verbose_name': 'Spent time', 'verbose_name_plural': 'Spent times'},
        ),
        migrations.AlterIndexTogether(
            name='dailyspenttime',
            index_together=set([('date', 'week_of_year', 'board', 'spent_time'), ('board', 'date', 'week_of_year', 'spent_time'), ('date', 'week_of_year', 'spent_time')]),
        ),
    ]
