# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_board_description'),
        ('dev_times', '0005_auto_20160925_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspenttime',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.CardComment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='dailyspenttime',
            name='uuid',
            field=models.CharField(max_length=128, null=True, verbose_name='External id of the card'),
        ),
    ]
