# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiboards', '0003_multiboard_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiboard',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='multiboards', to='members.Member', verbose_name='Members'),
        ),
    ]
