# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0065_auto_20170416_2026'),
        ('members', '0021_auto_20170319_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the multiboard')),
                ('description', models.TextField(blank=True, default='', max_length=128, verbose_name='Description of the multiboard')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived multiboards are not shown', verbose_name='This multiboard is archived')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order of this multiboard')),
                ('boards', models.ManyToManyField(related_name='multiboards', to='boards.Board', verbose_name='Boards')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_multiboards', to='members.Member', verbose_name='Member')),
            ],
        ),
    ]
