# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models

# Add multiboard creators to members
def add_creator_to_members(apps, schema):
    Multiboard = apps.get_model("multiboards", "Multiboard")
    for multiboard in Multiboard.objects.all():
        creator = multiboard.creator
        if not multiboard.members.filter(id=creator.id).exists():
            multiboard.members.add(creator)



class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20170319_1438'),
        ('multiboards', '0002_auto_20170504_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiboard',
            name='members',
            field=models.ManyToManyField(related_name='multiboards', to='members.Member', verbose_name='Members'),
        ),
        migrations.RunPython(add_creator_to_members)
    ]
