# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_auto_20160923_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMemberMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of mood measurement')),
                ('mood', models.CharField(choices=[('normal', ':-|'), ('happy', ':-)'), ('sad', ':-(')], default='normal', max_length=16, verbose_name='Mood of a member after one particular day')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_member_moods', to='members.Member', verbose_name='Member')),
            ],
        ),
    ]
