# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20160713_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Color of the label'),
        ),
    ]
