# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20160724_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='time',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Time this card is alive in the board in seconds.', max_digits=12, verbose_name='Time this card is alive in the board'),
        ),
    ]
