# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160726_1927'),
        ('boards', '0009_auto_20160727_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(related_name='cards', to='members.Member'),
        ),
    ]
