# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 21:23
from __future__ import unicode_literals

from django.db import migrations


def update_list_reports(apps, schema):
    ListReport = apps.get_model("boards", "ListReport")
    list_reports = ListReport.objects.all()
    for list_report in list_reports:
        list_report.board = list_report.list.board
        list_report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20160803_2012'),
    ]

    operations = [
        migrations.RunPython(update_list_reports)
    ]
