# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20160803_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listreport',
            name='board',
        ),
        migrations.RemoveField(
            model_name='listreport',
            name='list',
        ),
        migrations.RemoveField(
            model_name='memberreport',
            name='board',
        ),
        migrations.RemoveField(
            model_name='memberreport',
            name='member',
        ),
        migrations.DeleteModel(
            name='ListReport',
        ),
        migrations.DeleteModel(
            name='MemberReport',
        ),
    ]
