# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid


def set_unique_public_access_code(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    for board in Board.objects.all():
        board.public_access_code = "{0}{1}".format(shortuuid.ShortUUID().random(length=8), board.id).lower()
        board.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_auto_20160819_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='public_access_code',
            field=models.CharField(default='', help_text='With this code it is possible to access to a view with stats of this board', max_length=32, verbose_name='External id of the board'),
            preserve_default=False,
        ),
        migrations.RunPython(set_unique_public_access_code),
        migrations.AlterField(
            model_name='board',
            name='percentage_of_completion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Percentage of completion of project. Mind the percentage of completion of each requirement.', max_digits=10, null=True, verbose_name='Percentage of completion'),
        ),
    ]
