# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_auto_20160823_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='public_access_code',
            field=models.CharField(help_text='With this code it is possible to access to a view with stats of this board', max_length=32, unique=True, verbose_name='External id of the board'),
        ),
    ]
