# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20160923_2056'),
        ('boards', '0026_auto_20160921_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True, verbose_name='External id of the comment of this comment')),
                ('content', models.TextField(verbose_name='Content of the comment')),
                ('creation_datetime', models.DateTimeField(verbose_name='Creation datetime of the comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member author of this comment')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Card', verbose_name='Card this commenb belongs to')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
