# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_mood_value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Last mood value'),
        ),
        migrations.AddField(
            model_name='board',
            name='last_time_mood_was_computed',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last time mood was computed'),
        ),
    ]
