# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_auto_20161111_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='estimated_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Estimated time'),
        ),
        migrations.AddField(
            model_name='card',
            name='spent_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Spent time'),
        ),
    ]
