# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models


def update_after_development_lists(apps, schema):
    List = apps.get_model("boards", "List")
    List.objects.filter(type="after_development").update(type="after_development_in_review")


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_auto_20161112_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('ignored', 'Ignored'), ('backlog', 'Backlog'), ('ready_to_develop', 'Ready to develop'), ('development', 'In development'), ('after_development_in_review', 'After development (in review)'), ('after_development_waiting_release', 'After development (waiting release)'), ('done', 'Done'), ('closed', 'Closed')], default='ready_to_develop', max_length=64),
        ),
        migrations.RunPython(update_after_development_lists)
    ]
