# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0040_auto_20161112_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline'),
        ),
    ]
