# Generated by Django 1.10 on 2017-02-04 03:19


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirements", "0007_auto_20170204_0414"),
        ("boards", "0044_cardcomment_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcomment",
            name="requirement",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_comments",
                to="requirements.Requirement",
                verbose_name="Requirement this comment belongs to",
            ),
        ),
    ]
