# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0048_auto_20170211_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='header_image',
            field=models.ImageField(blank=True, default=None, help_text='Header image for this board. Optional.', null=True, upload_to=b'', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='board',
            name='show_on_slideshow',
            field=models.BooleanField(default=False, help_text='Select this checkbox if you want to show this board in the slideshow', verbose_name='Should this board be shown on the slideshow?'),
        ),
    ]
