# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_number_of_comments(apps, schema):
    Card = apps.get_model("boards", "Card")
    for card in Card.objects.all():
        card.number_of_comments = card.comments.all().count()
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_member_spent_time_factor'),
        ('boards', '0050_board_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number_of_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of comments of this card'),
        ),
        migrations.RunPython(set_number_of_comments)
    ]
