# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0054_auto_20170311_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='wip_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Maximum number of cards that should be in this list', null=True, verbose_name='Maximum WIP limit of this list'),
        ),
    ]
