# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0056_auto_20170311_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='valuation_comment',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valued_card', to='boards.CardComment'),
        ),
        migrations.AddField(
            model_name='card',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Value of this card for the client'),
        ),
    ]
