# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0058_auto_20170319_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardattachment',
            name='external_file_url',
            field=models.URLField(blank=True, default='', verbose_name='External file URL'),
        ),
        migrations.AlterField(
            model_name='cardattachment',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b'', verbose_name='File content'),
        ),
    ]
