# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0059_auto_20170321_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardattachment',
            name='external_file_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='External file name'),
        ),
    ]
