# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0060_auto_20170321_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardattachment',
            name='external_file_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='External file URL'),
        ),
    ]
