# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20170319_1438'),
        ('boards', '0061_auto_20170321_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='mentioned_members',
            field=models.ManyToManyField(related_name='mentioning_comments', to='members.Member', verbose_name='Mentioned members in this comment'),
        ),
    ]
