# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0065_auto_20170416_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardattachment',
            name='external_file_name',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='External file name'),
        ),
    ]
