# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def add_board_to_comments(apps, schema):
    CardComment = apps.get_model("boards", "CardComment")
    boards = {}
    for card_comment in CardComment.objects.all():
        board_id = card_comment.card.board_id
        if board_id not in boards:
            boards[board_id] = card_comment.card.board
        card_comment.board = boards[board_id]
        card_comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0066_auto_20170507_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_comments', to='boards.Board', verbose_name='Board this comment belongs to'),
        ),
        migrations.RunPython(add_board_to_comments)
    ]
