# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 16:44


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0067_auto_20170515_1839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardcomment",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_comments",
                to="boards.Board",
                verbose_name="Board this comment belongs to",
            ),
            preserve_default=False,
        ),
    ]
