# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Sum


# Set adjusted spent time initial value for each card
def set_card_adjusted_spent_time(apps, schema):
    Card = apps.get_model("boards", "Card")
    for card in Card.objects.all():
        card_adjusted_spent_time = card.daily_spent_times.all().\
            aggregate(adj_spent_time_sum=Sum("adjusted_spent_time"))["adj_spent_time_sum"]
        card.adjusted_spent_time = card_adjusted_spent_time
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0070_auto_20170530_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='adjusted_spent_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Adjusted spent time'),
        ),
        migrations.RunPython(set_card_adjusted_spent_time)
    ]
