# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurrent_cards', '0003_auto_20170603_0130'),
        ('boards', '0071_auto_20170530_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='parent_recurrent_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='recurrent_cards.RecurrentCard', verbose_name='Recurrent card'),
        ),
    ]
