# Generated by Django 6.0.1 on 2026-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0072_auto_20170603_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLabelRelationship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'boards_card_labels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardMemberRelationship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'boards_card_members',
                'managed': False,
            },
        ),
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        migrations.AlterField(
            model_name='board',
            name='header_image',
            field=models.ImageField(blank=True, default=None, help_text='Header image for this board. Optional.', null=True, upload_to='', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='board',
            name='identicon',
            field=models.ImageField(blank=True, default=None, help_text='Identicon for this board. It is automatically generated and stored.', null=True, upload_to='', verbose_name='Identicon'),
        ),
        migrations.AlterField(
            model_name='cardattachment',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='File content'),
        ),
    ]
