# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20161017_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartcache',
            name='uuid',
            field=models.CharField(help_text='Chart view name including some optional parameters', max_length=512, verbose_name='Chart view name'),
        ),
    ]
