# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20161017_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartCache',
            new_name='CachedChart',
        ),
    ]
