# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20161017_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedchart',
            name='uuid',
            field=models.CharField(help_text='Chart view name including some optional parameters', max_length=1024, verbose_name='Chart view name'),
        ),
    ]
