# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_cachedchart_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedchart',
            name='uuid',
            field=models.CharField(help_text='Chart view name including some optional parameters', max_length=2048, verbose_name='Chart view name'),
        ),
    ]
