# Generated by Django 6.0.1 on 2026-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0008_auto_20170530_1354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedchart",
            name="svg",
            field=models.FileField(
                upload_to="", verbose_name="SVG content of the chart"
            ),
        ),
    ]
