# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name for this hourly rate')),
                ('start_date', models.DateField(help_text='Start date of application of this billing rate per hour', verbose_name='Start date')),
                ('end_date', models.DateField(default=None, help_text='End date of application of this billing rate', null=True, verbose_name='End date')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Amount billed per hour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Should this billing rate should be applied?')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_hourly_rates', to='members.Member', verbose_name='Member')),
            ],
        ),
    ]
