# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_rates', '0002_auto_20160720_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlyrate',
            options={'ordering': ['start_date', 'end_date', 'name']},
        ),
    ]
