# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0032_auto_20161012_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(verbose_name='Creation datetime')),
                ('uuid', models.CharField(help_text='Chart view name including some optional parameters', max_length=256, verbose_name='Chart view name')),
                ('svg', models.FileField(upload_to=b'', verbose_name='SVG content of the chart')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_caches', to='boards.Board', verbose_name='Board')),
            ],
        ),
    ]
