# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20161017_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedchart',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cached_charts', to='boards.Board', verbose_name='Board'),
        ),
    ]
