# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='code',
            field=models.FileField(help_text='Upload a zip file with the directory that contains code that you want the system to assess', upload_to=b'', verbose_name='Code for this commit'),
        ),
    ]
