# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_auto_20160925_1843'),
        ('repositories', '0011_auto_20160925_1811'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='phpmdmessage',
            index_together=set([('commit', 'commit_file', 'ruleset'), ('board', 'repository', 'commit', 'commit_file', 'ruleset'), ('board', 'ruleset'), ('board', 'repository', 'commit', 'ruleset'), ('board', 'commit', 'commit_file', 'ruleset'), ('board', 'repository', 'ruleset', 'commit'), ('board', 'commit', 'ruleset')]),
        ),
    ]
