# Generated by Django 6.0.1 on 2026-01-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0014_auto_20161006_0143"),
    ]

    operations = []
