# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0064_auto_20170402_2123'),
        ('members', '0021_auto_20170319_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_spent_time', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Estimated spent time')),
                ('last_update_datetime', models.DateTimeField(verbose_name='Date this estimation was done')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='boards.Card', verbose_name='Card for this forecast')),
            ],
        ),
        migrations.CreateModel(
            name='Forecaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('model', models.CharField(max_length=32, verbose_name='Regression model')),
                ('formula', models.TextField(verbose_name='Formula')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Summary')),
                ('results_file', models.FileField(upload_to=b'', verbose_name='Field with the statsmodels results')),
                ('last_update_datetime', models.DateTimeField(verbose_name='Last update datetime')),
                ('board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasters', to='boards.Board', verbose_name='Board of this forecaster')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forecasters', to='members.Member', verbose_name='Member')),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasters', to='members.Member', verbose_name='Member of this forecaster')),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasters.Forecaster', verbose_name='Spent time for this forecast'),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together=set([('forecaster', 'card')]),
        ),
    ]
