# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='Value of this requirement'),
        ),
    ]
