# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_requirement_estimated_number_of_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='estimated_number_of_hours',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Cost in hours to complete this requirement.', null=True, verbose_name='Estimated number of hours to be completed'),
        ),
    ]
