# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_auto_20160823_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Private comments for the PM and the developers', verbose_name='Comments'),
        ),
    ]
