# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_requirement_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this requirement is not active it will treat  as a wish of the client but not as a real requirement', verbose_name='Is this requirement active?'),
        ),
    ]
