# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasters', '0002_auto_20170409_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecaster',
            name='last_updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_forecasters', to='members.Member', verbose_name='Member'),
        ),
    ]
