# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL for this video')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Number of times this video has been included in emails')),
            ],
        ),
    ]
