# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0014_auto_20160805_2004'),
        ('members', '0006_auto_20160726_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_movements', models.PositiveIntegerField(verbose_name='Forward movements')),
                ('backward_movements', models.PositiveIntegerField(verbose_name='Backward movements')),
                ('avg_card_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average time cards live in this list')),
                ('std_dev_card_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average time cards live in this list')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.Board', verbose_name='Board')),
                ('list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_reports', to='boards.List', verbose_name='List')),
            ],
        ),
        migrations.CreateModel(
            name='MemberReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.PositiveIntegerField(default=0, verbose_name='Number of assigned cards')),
                ('forward_movements', models.PositiveIntegerField(verbose_name='Forward movements')),
                ('backward_movements', models.PositiveIntegerField(verbose_name='Backward movements')),
                ('avg_card_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average time a card lives in the board')),
                ('std_dev_card_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Dev. time a card lives in the board')),
                ('avg_card_spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average card spent time')),
                ('std_dev_card_spent_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Deviation card spent time')),
                ('avg_card_estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Average task estimated card completion time')),
                ('std_dev_card_estimated_time', models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Std. Deviation of the estimated card completion time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='boards.Board', verbose_name='Board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='members.Member', verbose_name='Member')),
            ],
        ),
    ]
