# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20160925_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreport',
            name='backward_movements',
            field=models.PositiveIntegerField(default=0, verbose_name='Backward movements'),
        ),
        migrations.AlterField(
            model_name='memberreport',
            name='forward_movements',
            field=models.PositiveIntegerField(default=0, verbose_name='Forward movements'),
        ),
    ]
