# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_cardreview_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberreport',
            name='board',
        ),
        migrations.RemoveField(
            model_name='memberreport',
            name='member',
        ),
        migrations.AlterField(
            model_name='cardmovement',
            name='destination_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='boards.List', verbose_name='Destination list'),
        ),
        migrations.AlterField(
            model_name='cardmovement',
            name='source_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_movements', to='boards.List', verbose_name='Source list'),
        ),
        migrations.DeleteModel(
            name='MemberReport',
        ),
    ]
