# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interruption',
            name='board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Board', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='noisemeasurement',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Other comments about the noise in your environment'),
        ),
    ]
