# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_environment', '0003_auto_20160925_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruption',
            name='spent_time',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Spent time in this interruption'),
        ),
    ]
