# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=128, verbose_name='Trello API key')),
                ('api_secret', models.CharField(max_length=128, verbose_name='Trello API secret')),
                ('token', models.CharField(max_length=128, verbose_name='Trello token')),
                ('token_secret', models.CharField(max_length=128, verbose_name='Trello token secret')),
                ('uuid', models.CharField(max_length=128, verbose_name='Trello member uuid')),
                ('trello_username', models.CharField(max_length=128, verbose_name='Trello username')),
                ('initials', models.CharField(max_length=8, verbose_name='User initials in Trello')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Associated user')),
            ],
        ),
    ]
