# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='api_key',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Trello API key'),
        ),
        migrations.AlterField(
            model_name='member',
            name='api_secret',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Trello API secret'),
        ),
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Trello token'),
        ),
        migrations.AlterField(
            model_name='member',
            name='token_secret',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Trello token secret'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Associated user'),
        ),
    ]
