# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160722_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='real_working_hours_per_week',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Number of hours this developer should achieve eachweek'),
        ),
    ]
