# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_real_working_hours_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Trello API key'),
        ),
        migrations.AlterField(
            model_name='member',
            name='api_secret',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Trello API secret'),
        ),
        migrations.AlterField(
            model_name='member',
            name='real_working_hours_per_week',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Number of hours this developer should achieve eachweek'),
        ),
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Trello token'),
        ),
        migrations.AlterField(
            model_name='member',
            name='token_secret',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Trello token secret'),
        ),
    ]
