# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20160923_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='max_number_of_boards',
            field=models.PositiveIntegerField(default=None, help_text='Maximum number of boards this member can fetch. If null, unlimited number of boards', null=True, verbose_name='Max number of boards'),
        ),
    ]
