# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 23:26
from __future__ import unicode_literals

from dateutil.relativedelta import relativedelta
from django.db import migrations
from django.db.models import Min
from django.utils import timezone


def import_default_spent_time_factors(apps, schema):
    Member = apps.get_model("members", "Member")
    SpentTimeFactor = apps.get_model("members", "SpentTimeFactor")
    for member in Member.objects.filter(is_developer=True):
        if hasattr(member, "spent_time_factor"):
            factor = member.spent_time_factor
            first_work_date = (timezone.now() - relativedelta(years=40)).date()

            spent_time_factor = SpentTimeFactor(
                name=u"Default factor",
                member=member, factor=factor,
                start_date=first_work_date,
                end_date=None
            )
            spent_time_factor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0050_board_url'),
        ('members', '0016_spenttimefactor'),
    ]

    operations = [
        migrations.RunPython(import_default_spent_time_factors)
    ]
