# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20170225_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spenttimefactor',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date of this factor'),
        ),
    ]
